// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Experiences → Experience List*
 */
export interface ExperiencesDocumentDataExperienceListItem {
  /**
   * Title field in *Experiences → Experience List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.experience_list[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Experiences → Experience List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.experience_list[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Picture field in *Experiences → Experience List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.experience_list[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Iconic field in *Experiences → Experience List*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: experiences.experience_list[].iconic
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  iconic: prismic.BooleanField;
}

/**
 * Content for Experiences documents
 */
interface ExperiencesDocumentData {
  /**
   * Experience List field in *Experiences*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.experience_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_list: prismic.GroupField<
    Simplify<ExperiencesDocumentDataExperienceListItem>
  >;
}

/**
 * Experiences document from Prismic
 *
 * - **API ID**: `experiences`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperiencesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExperiencesDocumentData>,
    "experiences",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FaqSlice
  | AboutTripSlice
  | ItinerarySlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface PageDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = ExperiencesDocument | PageDocument;

/**
 * Item in *AboutTrip → Default → Primary → Sightseeing Highlights*
 */
export interface AboutTripSliceDefaultPrimarySightseeingHighlightsItem {
  /**
   * Title field in *AboutTrip → Default → Primary → Sightseeing Highlights*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.sightseeing_highlights[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Detail field in *AboutTrip → Default → Primary → Sightseeing Highlights*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.sightseeing_highlights[].detail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  detail: prismic.KeyTextField;
}

/**
 * Item in *AboutTrip → Default → Primary → Travel highlights*
 */
export interface AboutTripSliceDefaultPrimaryTravelHighlightsItem {
  /**
   * Title field in *AboutTrip → Default → Primary → Travel highlights*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.travel_highlights[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Detail field in *AboutTrip → Default → Primary → Travel highlights*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.travel_highlights[].detail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  detail: prismic.KeyTextField;
}

/**
 * Primary content in *AboutTrip → Default → Primary*
 */
export interface AboutTripSliceDefaultPrimary {
  /**
   * Title field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sightseeing Highlights field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.sightseeing_highlights[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sightseeing_highlights: prismic.GroupField<
    Simplify<AboutTripSliceDefaultPrimarySightseeingHighlightsItem>
  >;

  /**
   * Travel highlights field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.travel_highlights[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  travel_highlights: prismic.GroupField<
    Simplify<AboutTripSliceDefaultPrimaryTravelHighlightsItem>
  >;

  /**
   * Travel Cta field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.travel_cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  travel_cta: prismic.KeyTextField;

  /**
   * Travel CTA Link field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.travel_cta_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  travel_cta_link: prismic.KeyTextField;

  /**
   * Travel CTA Description field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.travel_cta_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  travel_cta_description: prismic.KeyTextField;
}

/**
 * Default variation for AboutTrip Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTripSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutTripSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutTrip*
 */
type AboutTripSliceVariation = AboutTripSliceDefault;

/**
 * AboutTrip Shared Slice
 *
 * - **API ID**: `about_trip`
 * - **Description**: AboutTrip
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTripSlice = prismic.SharedSlice<
  "about_trip",
  AboutTripSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → Questions*
 */
export interface FaqSliceDefaultPrimaryQuestionsItem {
  /**
   * Question field in *Faq → Default → Primary → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq → Default → Primary → Questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Questions field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryQuestionsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Key Features*
 */
export interface HeroSliceDefaultPrimaryKeyFeaturesItem {
  /**
   * Title field in *Hero → Default → Primary → Key Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.key_features[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary → Key Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.key_features[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *Hero → Default → Primary → Key Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.key_features[].icon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;

  /**
   * Tooltip field in *Hero → Default → Primary → Key Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.key_features[].tooltip
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tooltip: prismic.KeyTextField;

  /**
   * Link field in *Hero → Default → Primary → Key Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.key_features[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *Hero → Default → Primary → Guarantees*
 */
export interface HeroSliceDefaultPrimaryGuaranteesItem {
  /**
   * Icon field in *Hero → Default → Primary → Guarantees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.guarantees[].icon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary → Guarantees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.guarantees[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Illustration field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Key Features field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.key_features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  key_features: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryKeyFeaturesItem>
  >;

  /**
   * CTA Book Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_book_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_book_title: prismic.KeyTextField;

  /**
   * CTA Book Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_book_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_book_description: prismic.KeyTextField;

  /**
   * Trip code field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.trip_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  trip_code: prismic.KeyTextField;

  /**
   * Guarantees field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.guarantees[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  guarantees: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryGuaranteesItem>
  >;

  /**
   * CTA Book Local Currency field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_book_local_currency
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_book_local_currency: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Itinerary → Default → Primary → itinerary_list*
 */
export interface ItinerarySliceDefaultPrimaryItineraryListItem {
  /**
   * Title field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Location field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Experiences field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].experiences
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  experiences: prismic.ContentRelationshipField<"experiences">;

  /**
   * Illustration field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Arrival Transfer field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].arrival_transfer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  arrival_transfer: prismic.KeyTextField;

  /**
   * Welcome field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].welcome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  welcome: prismic.KeyTextField;

  /**
   * Accomodation field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].accomodation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accomodation: prismic.KeyTextField;

  /**
   * Included Meals field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].included_meals
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  included_meals: prismic.KeyTextField;

  /**
   * Departure Transfer field in *Itinerary → Default → Primary → itinerary_list*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[].departure_transfer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  departure_transfer: prismic.KeyTextField;
}

/**
 * Primary content in *Itinerary → Default → Primary*
 */
export interface ItinerarySliceDefaultPrimary {
  /**
   * Title field in *Itinerary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Caption field in *Itinerary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;

  /**
   * itinerary_list field in *Itinerary → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.default.primary.itinerary_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  itinerary_list: prismic.GroupField<
    Simplify<ItinerarySliceDefaultPrimaryItineraryListItem>
  >;
}

/**
 * Default variation for Itinerary Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItinerarySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ItinerarySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Itinerary*
 */
type ItinerarySliceVariation = ItinerarySliceDefault;

/**
 * Itinerary Shared Slice
 *
 * - **API ID**: `itinerary`
 * - **Description**: Itinerary
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItinerarySlice = prismic.SharedSlice<
  "itinerary",
  ItinerarySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ExperiencesDocument,
      ExperiencesDocumentData,
      ExperiencesDocumentDataExperienceListItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutTripSlice,
      AboutTripSliceDefaultPrimarySightseeingHighlightsItem,
      AboutTripSliceDefaultPrimaryTravelHighlightsItem,
      AboutTripSliceDefaultPrimary,
      AboutTripSliceVariation,
      AboutTripSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryQuestionsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryKeyFeaturesItem,
      HeroSliceDefaultPrimaryGuaranteesItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ItinerarySlice,
      ItinerarySliceDefaultPrimaryItineraryListItem,
      ItinerarySliceDefaultPrimary,
      ItinerarySliceVariation,
      ItinerarySliceDefault,
    };
  }
}
